openapi: '3.0.2'
info:
  title: Handiwork API
  version: '0.0.1'
servers:
  - url: https://localhost:8080/api/v1/
    description: Dev sever

paths:
  /craft_items:
    get:
      summary: Method for getting craft items list
      tags:
        - Craft items
      operationId: getAllCraftItems
      responses:
        '200':
          description: Successfull response with craft items list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Craft_Items'
        'default':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Method for creating a new craft item
      tags:
        - Craft items
      operationId: createCraftItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Craft_Item"
      responses:
        '200':
          description: Successfull response with a craft item object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Craft_Item'
        'default':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /craft_items/{item_id}:
    get:
      summary: Method for getting a craft item by item_id
      tags:
        - Craft items
      operationId: getCraftItemById
      parameters:
        - name: item_id
          in: path
          required: true
          description: Craft Item identifier
          schema:
            type: string
            example: 58f38e03-fe40-42f0-bc81-4ed840a40ac5
      responses:
        '200':
          description: Successfull response with a craft item object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Craft_Item'
        'default':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Craft item deleting method
      tags:
        - Craft items
      operationId: deleteCraftItemById
      parameters:
        - name: item_id
          in: path
          required: true
          description: Craft Item identifier
          schema:
            type: string
            example: 58f38e03-fe40-42f0-bc81-4ed840a40ac5
      responses:
        '200':
          description: Successfull craft item delete
          content:
            application/json: {}
        'default':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Craft_Item:
      type: object
      required:
        - name
        - created_at
      properties:
        item_id:
          type: string
          example: 58f38e03-fe40-42f0-bc81-4ed840a40ac5
        name:
          type: string
          example: Patchwork ball
        category:
          type: string
          enum:
            - toys
            - blankets
            - pillows
          description: Craft item category
          example: toys
        created_at:
          type: string
          format: 2022-07
          example: 2022-11
        image:
          type: string
          example: https://i.imgur.com/mjUGwrX.jpg
        making_time:
          type: string
          example: 2h
        skill_req:
          type: integer
          example: 1
    Craft_Items:
      type: array
      items:
        $ref: '#/components/schemas/Craft_Item'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string